### ISSUE TITLE
remove polygons as they grow older

### ISSUE THREAD

**Issue by jmigueldelgado** [jmigueldelgado/buhayra#41]
older polygons, eg older that 2 months should be deleted from the data base. The remaining information should be kept though!

**Comment by jmigueldelgado** [comment]
this is being implemented in branch rm-old-polygons. Currently showing a bug:

```
  request="""INSERT INTO """ + location['region'] + """ SELECT id, ingestion_time, area, threshold, wmxjrc_area, id_jrc, source_id FROM """ + location['postgis_db'] + """ ON CONFLICT DO NOTHING;"""

    # following error occurs for this request:
        # NotNullViolation: null value in column "id" violates not-null constraint
        # DETAIL:  Failing row contains (null, 2019-03-23 18:26:52+01, 0, 0, 0, 644, S1A).
```

**Comment by jmigueldelgado** [comment]
another error:

>   File "/home/delgado/proj/buhayra_sib/maintenance/move_stuff_around.py", line \
70, in update_db
    conn = psycopg2.connect(host=postgis_host,dbname='watermasks',user=postgis_\
user,password=postgis_pass)
  File "/home/delgado/local/miniconda3/envs/buhayra/lib/python3.6/site-packages\
/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No route to host
        Is the server running on host "141.89.96.193" and accepting
        TCP/IP connections on port 5432?

**Comment by schuem** [comment]
Some IPs have changed due to an IT crash...

**Comment by jmigueldelgado** [comment]
thanks martin! I had updated the IPs previously. I think this issue only occurred once and I could not replicate it so I assume it was just some down time or network problem. It now works. Back to https://github.com/jmigueldelgado/buhayra/issues/41#issuecomment-524352492 ...
