### ISSUE TITLE
create sftp connection using rsa or private credentials

### ISSUE THREAD

**Issue by jmigueldelgado** [jmigueldelgado/buhayra#8]
transfer data from orson2 to webserver without authenticating every time.

I would like to obtain the watermasks from orson and copy them to the webserver. Using RSA or private credentials within the webserver would be great. The idea is that we do not have to insert a password so it can run from cron

**Comment by schuem** [comment]
If you would send me the credentials for both servers, i could set up the ssh keys. Should be pretty straightforward.
